-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

UPDATE admin_users SET password_hash = crypt('BENJIA2024', gen_salt('bf')) WHERE username = 'admin';